apiVersion: v1
kind: LimitRange
metadata:
  name: namespace-limits
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
